COHERE_API_KEY = "VfibPsP2V6iykQYmhJ7T3Xmd9pZwjxtQeiMtM4fW"
COHERE_MODEL = "command-r-plus"

GROQ_API_KEY = "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"

NEO4J_URI = "bolt://44.202.207.133:7687"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "fellows-engineers-room"